---
- name: Java app
  host: dev
  become: yes
  tasks:
  - name: Git clone
    ansible.builtin.git:
      repo: https://github.com/koddas/war-web-project.git
      dest: /test
  - name: maven
    apt: 
      name: maven 
      state: psesent
  

